version: "3.8"

services:
  # -------------------- FastAPI Backend --------------------
  # app:
  #   build: ./app
  #   container_name: backend_api
  #   restart: unless-stopped
  #   ports:
  #     - "8080:80"
  #   env_file:
  #     - .env
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # -------------------- MySQL Database --------------------
  # db only docker compose up -d database
  database:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - app-network

# -------------------- Networks --------------------
networks:
  app-network:
    driver: bridge

# -------------------- Volumes --------------------
volumes:
  mysql_data: